kind: pipeline
name: default

steps:
- name: Build (Clang)
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - export CC=/usr/bin/clang
  - export CXX=/usr/bin/clang++
  - $CC --version
  - apt update && apt install -y libsfml-dev
  - cmake -B build/clang -DCMAKE_CXX_COMPILER="$CXX" -G "Unix Makefiles" .
  - cmake --build build/clang

- name: Build (GCC)
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - $CC --version
  - apt update && apt install -y libsfml-dev
  - cmake -B build/gcc -DCMAKE_CXX_COMPILER="$CXX" -G "Unix Makefiles" .
  - cmake --build build/gcc
